name             'role-mongodb-shard2'
maintainer       'Stephen Van Zee'
maintainer_email 'svanzee@caringbridge.org'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-shard2'
long_description 'Installs/Configures role-mongodb-shard2'
version          '0.1.1'

depends 'mongodb', '0.16.1'
depends 'yum'
